n= as.integer(readline("Enter the number of employees"))
empid = vector(mode="character",length =n)
name = vector (mode ="character",length=n)
empcode=vector(mode="integer",length=n)
doj =vector (mode="character",length=n)
deptname =vector (mode="character",length=n)
desig =vector (mode="character",length=n)

print("Enter EmpID")
for(i in 1:n)
  empid[i]=as.integer(readline())
print("enter Emp Name")
for(i in 1:n)
  name[i]=as.character(readline(""))
print("Enter Employee Code")
for(i in 1:n)
  empcode[i]=as.integer(readline())
print("Enter emp Date of Joining")
for(i in 1:n)
  doj[i]=as.character(readline(prompt = " "))
print("Enter emp Department")
for(i in 1:n)
  deptname[i]=as.character(readline(prompt = " "))
print("Enter Designation")
for(i in 1:n)
  desig[i]=as.character(readline(prompt = " "))

employee=data.frame(empid,name,empcode,doj,deptname,desig)
print(employee)

write.csv(employee,"/home/student/Anurag/Emp.csv")

readEmp=read.csv("/home/student/Anurag/Emp.csv")
print(readEmp)

i = as.integer(readline("EmpID"))
n = as.character(readline("Name"))
c=as.integer(readline("Emp Code"))
d =as.character(readline("Date of Join"))
a =as.character(readline("Dept"))
s =as.character(readline("Designation"))
x=data.frame(i,n,c,d,a,s)
write.table(x,"/home/student/Anurag/Emp.csv",col.names = FALSE,append = T,row.names = T,quote = FALSE,sep = ",")

readEmp=read.csv("/home/student/Anurag/Emp.csv")
print(readEmp)
